[update to 1.8.1] Fix #5418: Incorrect default path for sphinx-build -d/doctrees files
Jean-François B (1):
      Merge pull request #5455 from jfbu/5453_PDF_howto_pagenumbers

Jon Dufresne (1):
      Correct capitalization of PyPI

Takeshi KOMIYA (40):
      Bump version
      Fix #5421: autodoc emits deprecation warning for :confval:`autodoc_default_flags`
      Fix #5418: Incorrect default path for sphinx-build -d/doctrees files
      Merge pull request #5425 from tk0miya/5418_incorrect_doctreedir
      Merge branch '1.8' into 5421_warning_for_autodoc_default_flags
      Merge pull request #5424 from tk0miya/5421_warning_for_autodoc_default_flags
      Fix #5422: lambda object causes PicklingError on storing environment
      Fix typo
      Merge pull request #5430 from tk0miya/fix_typo
      Merge pull request #5429 from tk0miya/5422_pickling_error
      Fix #5417: Sphinx fails to build with syntax error in Python 2.7.5
      Fix #5433: latex: ImportError: cannot import name 'DEFAULT_SETTINGS'
      Merge pull request #5443 from tk0miya/5417_crashed_with_py275
      Fix mypy violations
      Merge pull request #5452 from tk0miya/mypy-0.630
      Fix #4911: add latexpdf to make.bat for non make-mode
      test: Move EnumCls to target.enum package
      Fix #5436: Autodoc does not work with enum subclasses with properties/methods
      Fix #5431: autodoc: ``autofunction`` emits a warning for callable objects
      Fix #5437: autodoc: crashed on modules importing eggs
      Merge pull request #5451 from tk0miya/4911_help_for_nonmakemode
      Merge branch '1.8' into 5436_attributes_for_enum_subclasses
      Merge pull request #5449 from tk0miya/5436_attributes_for_enum_subclasses
      Merge branch '1.8' into 5437_autodoc_crashed_for_egg_packages
      Merge pull request #5442 from tk0miya/5437_autodoc_crashed_for_egg_packages
      Merge branch '1.8' into 5433_latex_ImportError
      Merge pull request #5445 from tk0miya/5433_latex_ImportError
      Merge branch '1.8' into 5431_warnings_for_callable
      Merge pull request #5447 from tk0miya/5431_warnings_for_callable
      Update CHANGES for PR #5457
      Fix #5463: mathbase: math_role and MathDirective was disappeared in 1.8.0
      Merge pull request #5464 from tk0miya/5463_deprecate_math_role
      Fix #5454: latex: Index has disappeared from PDF for Japanese documents
      Merge pull request #5465 from tk0miya/5454_disappeared_index_in_latexpdfja
      Fix #5432: py domain: :type: field can't process :term: references
      Fix py domain: TypeError has been raised for class attribute (ref: #5426)
      Merge pull request #5467 from tk0miya/5432_attribute_type_disallows_termref
      Merge branch '1.8' into 5426_TypeError_for_class_attributes
      Merge pull request #5468 from tk0miya/5426_TypeError_for_class_attributes
      Bump to 1.8.1 final

Zejun Wu (1):
      Fix TypeError in error message when override is prohibited

jfbu (4):
      Fix #5453 and move LaTeX ``\pagestyle`` to template
      Merge branch '1.8' into 5453_PDF_howto_pagenumbers
      Update CHANGES for #5455
      Fix typo in make.bat template help string, update help strings

Release 1.8.1 (released Sep 22, 2018)
=====================================

Incompatible changes
--------------------

* LaTeX ``\pagestyle`` commands have been moved to the LaTeX template. No
  changes in PDF, except possibly if ``\sphinxtableofcontents``, which
  contained them, had been customized in :file:`conf.py`. (refs: #5455)

Bugs fixed
----------

* #5418: Incorrect default path for sphinx-build -d/doctrees files
* #5421: autodoc emits deprecation warning for :confval:`autodoc_default_flags`

(NEWS truncated at 15 lines)